CFLAGS = -g -target riscv64 -march=rv64i -I$(MUSL_INSTALL_PATH)/include

all: template

template: template.o
	ld.lld-$(CLANG_VERSION) -o template \
		$(MUSL_INSTALL_PATH)/lib/crt1.o \
		$(MUSL_INSTALL_PATH)/lib/libc.a \
		$(COMPILER_RT_PATH) \
		*.o

template.o: template.c
	clang-$(CLANG_VERSION) $(CFLAGS) -c template.c

clean:
	rm -f template *.o
